version: 2
jobs:
  build-common: &common-build
    docker:
      - image: node
    working_directory: ~/sinon
    steps:
      - run:
          name: Versions
          command: |
            npm version
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-npm-master-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
              npm config set strict-ssl false
              # puppeteer install script throws syntax errors for Node v4
              # https://github.com/GoogleChrome/puppeteer/blob/f19e2ade0d4859435422131905e932abe3db199c/install.js#L66
              if node --version | grep -q '^v4'; then
                npm config set ignore-scripts true
                npm install
                npm config set ignore-scripts false
              else
                npm install
              fi
      - run:
          name: Pre-Test
          # ESLint only supports Node >=4
          command: |
              if node --version | grep -q '^v6'; then
                npm run lint;
                npm run test-headless -- --allow-chrome-as-root;
                npm run test-webworker -- --allow-chrome-as-root;
              fi
      - run:
          name: Test
          command: npm run test-node
      - save_cache:
          key: v2-npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  node-4:
    <<: *common-build
    docker:
      - image: node:4

  node-6:
    <<: *common-build
    docker:
      - image: node:6

  node-8:
    <<: *common-build
    docker:
      - image: node:8
    environment:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

workflows:
  version: 2
  build:
    jobs:
      - node-4
      - node-6
      - node-8
