version: 2
jobs:
  build-common: &common-build
    docker:
      - image: node
    working_directory: ~/sinon
    steps:
      - run:
          name: Versions
          command: |
            npm version
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-npm-master-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
              npm config set strict-ssl false
              npm install

              if node --version | grep -q '^v6'; then
                wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
                echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
                apt-get update
                apt-get install -y --no-install-recommends google-chrome-unstable
              fi
      - run:
          name: Pre-Test
          # ESLint only supports Node >=4
          command: |
              if node --version | grep -q '^v6'; then
                npm run lint;
                npm run test-headless -- --chrome $(which google-chrome-unstable);
                npm run test-webworker;
              fi
      - run:
          name: Test
          command: npm run test-node
      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  node-4:
    <<: *common-build
    docker:
      - image: node:4
    environment:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

  node-6:
    <<: *common-build
    docker:
      - image: node:6

  node-8:
    <<: *common-build
    docker:
      - image: node:8
    environment:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

workflows:
  version: 2
  build:
    jobs:
      - node-4
      - node-6
      - node-8
