title: Sinon.JS
description: |
  Standalone test spies, stubs and mocks for JavaScript.
    Works with any unit testing framework.
url: 'https://sinonjs.org'
github_username: sinonjs
sinon:
  current_release: v1.17.6
  next_release: v2.0.0-pre.5
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: none
  syntax_highlighter_opts:
    disable: true
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - release-source
collections:
  howto:
    output: true
    permalink: '/how-to/:path/'
  releases:
    output: true
    permalink: '/:collection/:path/'
